const SPARK_SOLUTIONS = {
  "spark-mount": {name:"Spark Mount™",summary:"Professional TV mounting and home entertainment installation for residential customers.",purpose:"Spark Mount™ transforms TVs, soundbars, media devices, cables, and related entertainment components into a clean, secure, usable, and professionally finished setup.",problem:"I want my TV and entertainment setup mounted cleanly, safely, and professionally without a messy or unfinished result.",included:["TV mounting","Soundbar mounting","Wire-concealment options where conditions and scope allow","Fireplace-area TV installations where conditions support an approved installation","Media setup and cable management","Placement review, testing, and customer walkthrough"],excluded:["Structural engineering, reinforcement, or wall reconstruction","Electrical relocation, new power installation, or in-wall power work outside current licensed scope","Unsafe or unsuitable wall-cavity concealment","Manufacturer warranty service or defective-equipment repair","Drywall, painting, masonry, carpentry, or finish construction unless separately approved","Commercial AV programs or surveillance work"],outcome:"A clean, secure, professionally installed entertainment setup that is planned, mounted, organized, tested, explained, and completed with professional care."},
  "spark-connect": {name:"Spark Connect™",summary:"Reliable residential networking and connectivity support.",purpose:"Spark Connect™ improves how the customer's home connects, communicates, and performs through better Wi-Fi, cleaner network organization, and more dependable connected systems.",problem:"My home network is unreliable, confusing, messy, or not performing the way it should.",included:["Residential router installation and setup","Mesh Wi-Fi installation and configuration","Ethernet installation that directly supports residential connectivity","Network optimization and rack cleanup","Wi-Fi troubleshooting and supported-device connectivity","Testing and clear customer explanation"],excluded:["Internet-provider, speed, or outage guarantees","Managed IT, commercial IT, or enterprise networking","Cybersecurity guarantees, monitoring, or managed security","Ongoing network administration or monthly support","Unsupported-equipment repair or warranty service","Unapproved account, credential, electrical, wall-access, or cabling work"],outcome:"A more reliable, cleaner, better explained, and more serviceable home network within approved scope."},
  "spark-home": {name:"Spark Home™",summary:"Professional smart home installation and setup for residential customers.",purpose:"Spark Home™ installs, configures, and explains supported smart home devices so customers can use connected home technology with less confusion and greater confidence.",problem:"I want smart home devices installed and set up correctly so they work together simply and reliably.",included:["Supported smart-switch installation and setup","Supported smart-dimmer installation and setup","Supported smart-thermostat installation and setup where conditions are appropriate","Supported smart-doorbell installation and setup where scope allows","Supported-device configuration and integration","Testing and customer walkthrough"],excluded:["Security cameras, surveillance, alarm, access-control, or regulated security work","Manufacturer warranty service or defective-device repair","Unsupported-device, platform, app, or subscription guarantees","Unapproved account or credential handling","Cybersecurity guarantees or managed IT","Electrical or HVAC work outside current approved scope"],outcome:"Supported smart home technology installed, connected, tested, and explained within approved scope."},
  "spark-illuminate": {name:"Spark Illuminate™",summary:"Professional landscape lighting solutions for residential customers.",purpose:"Spark Illuminate™ makes outdoor spaces more attractive, usable, visible, and dependable while preserving clean installation standards and clear customer communication.",problem:"I want outdoor lighting that looks good, works reliably, and improves how my property feels and functions at night.",included:["Lighting consultation","Approved landscape-lighting installation","Appropriate transformer replacement or improvement","Landscape-lighting troubleshooting","System organization, placement, dependability, or usability improvements","Testing and customer walkthrough"],excluded:["Final landscape-design authority or architectural lighting design","Utility locating, excavation responsibility, irrigation, hardscape, or landscape restoration","Unsafe or out-of-scope electrical work","Work requiring licensing, permitting, or inspection outside approved scope","Unsupported-equipment warranty service or repair","Regulated security or surveillance lighting work"],outcome:"Outdoor lighting that is more beautiful, dependable, understandable, and appropriate for the approved scope."},
  "spark-wire": {name:"Spark Wire™",summary:"Professional low-voltage infrastructure for residential customers.",purpose:"Spark Wire™ provides structured wiring, Ethernet cabling, low-voltage wiring, cable organization, and wiring upgrades that make home technology infrastructure cleaner, more reliable, easier to service, and better prepared for future needs.",problem:"My home technology wiring is missing, messy, unreliable, outdated, or not ready for what I need next.",included:["Approved structured wiring","Ethernet cabling where routes and conditions support the work","Approved low-voltage wiring","Cable organization","Wiring upgrades within approved scope","Documentation support where required"],excluded:["High-voltage electrical work outside current licensed scope","Commercial cabling or enterprise infrastructure","Fire alarm, access control, alarm, surveillance, or regulated security cabling","Unsafe or inaccessible routes","Code, permitting, or inspection commitments","Drywall, painting, masonry, carpentry, or finish construction unless separately approved"],outcome:"Cleaner, more organized, more serviceable, and more future-ready home technology infrastructure within approved scope."},
  "spark-restore": {name:"Spark Restore™",summary:"Diagnostics and improvement for existing home technology systems.",purpose:"Spark Restore™ restores the performance, reliability, and functionality of existing home technology systems through professional diagnostics, troubleshooting, repair, optimization, and reconfiguration.",problem:"My technology used to work. Now it doesn't.",included:["Technology diagnostics","Residential Wi-Fi and smart-home troubleshooting","Supported TV, media, and device troubleshooting","Approved device reconfiguration","Low-voltage troubleshooting and network optimization","Existing-system cleanup and practical improvements"],excluded:["Manufacturer warranty service or unsupported-equipment repair","Commercial or managed IT services","Ongoing administration, monthly support, or monitoring","Cybersecurity guarantees or managed security","Electrical or regulated security work outside current scope","Third-party platform, provider, manufacturer, or unsupported-device guarantees"],outcome:"A clear understanding of what was wrong, what was corrected, what remains unresolved, and the recommended next step—with technology performing more reliably where approved scope allows."}
};

const solution = SPARK_SOLUTIONS[document.body.dataset.solution];
if (solution) {
  document.title = `${solution.name.replace("™", "")} | Spark Electric`;
  document.querySelector('meta[name="description"]').content = `${solution.summary} ${solution.outcome}`;
  for (const [selector, value] of Object.entries({"[data-solution-name]":solution.name,"[data-solution-summary]":solution.summary,"[data-solution-purpose]":solution.purpose,"[data-solution-problem]":`“${solution.problem}”`,"[data-solution-outcome]":solution.outcome})) document.querySelector(selector).textContent = value;
  document.querySelector("[data-solution-included]").innerHTML = solution.included.map(item => `<li>${item}</li>`).join("");
  document.querySelector("[data-solution-excluded]").innerHTML = solution.excluded.map(item => `<li>${item}</li>`).join("");
}
